<?php

/**
 * @file
 * Install, update and uninstall functions for the doghouse drupal 8 installation profile.
 */

/**
 * Implements hook_install().
 *
 * Perform actions to set up the site for this profile.
 *
 * @see system_install()
 */
function doghouse_standard_install() {

  // First, do everything that is done in the standard profile.
  include_once DRUPAL_ROOT . '/core/profiles/standard/standard.install';
  standard_install();
}
